### ISSUE TITLE
Method to crack pdf is not found

### ISSUE THREAD

**Issue by Multipleriver** [34j/decryptpdf#21]
### Is your feature request related to a problem? Please describe.

# Method to crack pdf is not found
Sorry to bother you, may I ask where is the fuction of cracking a pdf file or removing its password?
My file path is `E:\envs\pdfrip\Input\yy.pdf`.
When I enter  `decryptpdf E:\envs\pdfrip\Input` in cmd, it needs me to input the password rather than removes password for me.
![image](https://github.com/34j/decryptpdf/assets/97719454/7b126d02-e36f-4cc5-9e94-e6346d340eb9)
Could you tell me how to use this tool to remove the password of a pdf file?
Thanks! 

### Describe alternatives you've considered

xx

### Additional context

![image](https://github.com/34j/decryptpdf/assets/97719454/6798866c-d1ab-4548-b40e-9915dade54a6)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Are you willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time, and I know how to start.
- [ ] Yes, I have the time, but I don't know how to start. I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [X] No, I don't have the time and I wouldn't even know how to start.

**Comment by 34j** [comment]
This tool is not intended for cracking; please use other dedicated tools such as John the Ripper.
